config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new { |user| user.patient? } do
    root to: "patient/home#show"
  end
  constraints Clearance::Constraints::SignedIn.new { |user| user.doctor? } do
    root to: "doctor/home#show"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "home#show"
  end
  resources :stripe_customers, only: [:new, :create]
  resources :chat_rooms, only: [:show] do
    get 'activate' => 'chat_rooms#activate'
    get 'deactivate' => 'chat_rooms#deactivate'
    resources :messages, only: [:create]
  end
  namespace :patient do
    resources :patients, only: [:new, :create]
    resources :doctors, only: [:show]
    resources :chat_rooms, only: [:create] do
      resources :chat_charges, only: [:new] do
        get 'stripe' => 'chat_charges#stripe', on: :collection
        post 'stripe' => 'chat_charges#stripe', on: :collection
        get 'paypal' => 'chat_charges#paypal', on: :collection
        get 'paypal_success' => 'chat_charges#paypal_success', on: :collection
      end
    end
  end

  namespace :doctor do
    resources :doctors, only: [:new, :create, :edit, :update]
  end
  get 'users/self/edit' => 'users#edit'

end

app/models/doctor.rb
class Doctor < User
  validates :name, :province, :num, :med_id, :studio_address, :city, :zip_code, presence: true
  before_create :set_patient_id
  before_save :set_approvement

  def set_approvement
    if zip_code && email && name
      self.approved = true
    end
  end

  def set_patient_id
    self.patient_id = "ID" + SecureRandom.hex(6).upcase
  end

  def password_optional?
    true
  end

  def authenticated?(password)
    password == patient_id
  end
end

app/controllers/doctor/application_controller.rb
class Doctor::ApplicationController < ApplicationController
  before_action :require_logged_user
  before_action :require_approved_user
  before_action :require_doctor

  protected

  def require_doctor
    unless current_user.is_a? Doctor
      redirect_to root_path, alert: 'You should be a doctor to get this page'
    end
  end
end

app/controllers/doctor/doctors_controller.rb
class Doctor::DoctorsController < Doctor::ApplicationController
  skip_before_action :require_logged_user, only: [:new, :create]
  skip_before_action :require_approved_user, only: [:new, :create]
  skip_before_action :require_doctor, only: [:new, :create]
  before_action :find_doctor, only: [:edit, :update]

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.type = Doctor

   if @doctor.save
     sign_in @doctor
     redirect_back_or root_path
   else
     render :new
   end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to root_path
    else
      render :edit
    end
  end


  private

  def find_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(
      :zip_code, :name, :email, :password, :phone,
      :province, :num, :med_id, :studio_address, :city,
      :video_chat_rate
    )
  end
end

app/controllers/doctor/home_controller.rb
class Doctor::HomeController < Doctor::ApplicationController
  def show
    @chats = ChatRoom.includes(:messages).where(doctor: current_user).limit(5).map do |chat|
      chat if chat.messages.any? && chat.messages.first.author != current_user
    end.compact

    @number_of_patients = @chats.map(&:patient_id).uniq.count
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/patient/doctors_controller.rb
class Patient::DoctorsController < Patient::ApplicationController
  before_action :require_logged_user
  before_action :require_approved_user

  def show
    @doctor = User.find(params[:id])
  end
end

app/controllers/patient/home_controller.rb
class Patient::HomeController < Patient::ApplicationController

  def show
    ids = Doctor.pluck(:id).map { |id| id if $redis_onlines.exists(id) }.compact
    @doctors = Doctor.where(id: ids)
  end
end

app/views/doctor/home/show.html.erb
<div id="screen14" class="screen">
  <div class="container">
    <main id="content">
      <div class="panel-container">
        <div class="panel-col">
          <div id="panel-bio" class="panel"><%= image_tag "dummydoctor.jpg" %>
            <div class="doctor-bio">
              <p>
                È professore emerito
                all'Università di Harvard
                ed autore di innumerevoli
                pubblicazioni scientifiche
                sulle droghe ed in
                particolare sull'uso
                terapeutico e non della
                cannabis quali Psychedelic
                Drugs Reconsidered e
                Marijuana: La medicina.
              </p><a href="#" class="more">more</a>
            </div>
            <h3 class="doctor-name"><%= current_user.name %></h3>
            <p class="doctor-occupation"><% current_user.province %></p>
          </div>
          <div id="panel-schedule" class="panel">
            <div class="doctor-item">
              <h3>Fees</h3>
              <p>Video Chat Consultation: <strong><%= number_to_currency current_user.video_chat_rate, unit: '' %> euro</strong></p>
              <p>Prescription: <strong><%= number_to_currency current_user.prescription_rate, unit: '' %> euro</strong></p><a href="#" class="edit"><%= image_tag "edit.png" %></a>
            </div>
            <div class="doctor-item">
              <h3>Schedule</h3>
              <p><strong>Mon. </strong>16.00 - 18.00</p>
              <p><strong>Fri. </strong>16.00 - 18.00</p><a href="#" class="edit"><%= image_tag "edit.png" %></a>
            </div>
          </div>
        </div>
        <div class="panel-col">
          <div id="panel-summary" class="panel"><a href="#" class="maximize"><%= image_tag "maximize.png" %></a>
            <h3><span>08</span>Tuesday</h3>
            <div class="stat-container">
              <div class="stat">
                <div class="stat-title">Today</div>
                <div class="stat-value">4</div>
              </div>
              <div class="stat">
                <div class="stat-title">Appointments</div>
                <div class="stat-value">23</div>
              </div>
              <div class="stat">
                <div class="stat-title">This week</div>
                <div class="stat-value">6</div>
              </div>
              <div class="stat">
                <div class="stat-title">Last two weeks</div>
                <div class="stat-value">32</div>
              </div>
            </div>
          </div>
          <div id="panel-dateswitcher" class="panel"><a href="#" class="bottom"><%= image_tag "bottom.png" %></a>
            <div class="dates"><a href="#" class="date">day</a><a href="#" class="date">month</a><a href="#" class="date">week</a></div>
          </div>
          <div id="panel-templates" class="panel"><a href="#" class="maximize"><%= image_tag "maximize.png" %></a>
            <h3>My Templates</h3>
            <p class="templates-count">17</p>
            <div class="templates"><a href="#" class="template"><%= image_tag "prescription.png" %></a><a href="#" class="template"><%= image_tag "prescription.png" %></a><a href="#" class="template"><%= image_tag "prescription.png" %></a></div>
          </div>
          <div id="panel-activity" class="panel"><a href="#" class="maximize"><%= image_tag "maximize.png" %></a>
            <h3>Activity</h3>
            <div class="activity-buttons"><a href="#" class="online">Online</a><a href="#" class="offline">Offline</a></div>
          </div>
        </div>
        <div class="panel-col">
          <div id="panel-patients" class="panel">
            <div class="panel-head"><a href="#" class="maximize"><%= image_tag "maximize.png" %></a></div>
            <div class="panel-body">
              <h3>My Patients</h3>
              <div class="patients-count"><%= @number_of_patients %></div>
            </div>
          </div>
          <div id="panel-chat" class="panel">
            <div class="panel-head"><a href="#" class="maximize"><%= image_tag "maximize.png" %></a></div>
            <div class="panel-body">
              <h3>Chat<span class="chat-count"><%= @chats.count %></span></h3>
              <div class="chats">
                <% @chats.each do |chat| %>
                  <%= link_to chat_room_path(chat), class: 'chat-item' do %>
                    <div class="unread"></div>
                    <div class="chat-author"><%= chat.messages.first.author.name %></div>
                    <div class="chat-text"><%= chat.messages.first.body %><span class="excerpt">...</span></div>
                  <% end %>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer id="footer">
      <div class="brand">We.</div>
      <nav id="nav"><a href="#">About</a><a href="#">How to use</a><a href="#">Contacts</a></nav>
    </footer>
  </div>
</div>