config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new { |user| user.patient? } do
    root to: "patient/home#show"
  end
  constraints Clearance::Constraints::SignedIn.new { |user| user.doctor? } do
    root to: "doctor/home#show"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "home#show"
  end
  resources :stripe_customers, only: [:new, :create]
  resources :chat_rooms, only: [:show] do
    get 'activate' => 'chat_rooms#activate'
    get 'deactivate' => 'chat_rooms#deactivate'
    resources :messages, only: [:create]
  end
  namespace :patient do
    resources :patients, only: [:new, :create]
    resources :doctors, only: [:show]
    resources :chat_rooms, only: [:create] do
      resources :chat_charges, only: [:new] do
        get 'stripe' => 'chat_charges#stripe', on: :collection
        post 'stripe' => 'chat_charges#stripe', on: :collection
        get 'paypal' => 'chat_charges#paypal', on: :collection
        get 'paypal_success' => 'chat_charges#paypal_success', on: :collection
      end
    end
  end

  namespace :doctor do
    resources :doctors, only: [:new, :create, :edit, :update]
  end
  get 'users/self/edit' => 'users#edit'

end

app/views/shared/_doctor_left_menu.html.erb
<div class="left_menu">
  <div class="left_menu-top_part">
    <h4>Role: <%= current_user.role%></h4>

    <div class="list-group">
      <a href="#" class="list-group-item">My appointments</a>
      <a href="#" class="list-group-item">My Patients</a>
      <a href="#" class="list-group-item">My Prescriptions</a>
      <a href="#" class="list-group-item">Documents</a>
      <%= link_to "Edit Account", edit_doctor_doctor_path(current_user), class: 'list-group-item' %>
      <%= link_to "Sign out", sign_out_path, method: :delete, class: 'list-group-item' %>
    </div>
  </div>
</div>

app/views/shared/_patient_left_menu.html.erb
<div class="left_menu_patient">
  <div class="left_menu-top_part">
    <h4>Role: <%= current_user.role %></h4>

    <div class="list-group">
      <%- Doctor.find_each do |doctor| %>
        <%= link_to patient_doctor_path(doctor), class: 'list-group-item' do %>
          <%= doctor.name %>
          <span class="pull-right"><%= availability_status doctor %></span>
        <% end %>
      <% end %>
      <%= link_to "Sign out", sign_out_path, method: :delete, class: 'list-group-item' %>
    </div>
  </div>
</div>

app/views/shared/_user_identification.html.erb
<div class="left_menu">
  <div class="left_menu-top_part">
    You are talking with <%= user.name %>
  </div>
</div>