config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new { |user| user.patient? } do
    root to: "patient/home#show"
  end
  constraints Clearance::Constraints::SignedIn.new { |user| user.doctor? } do
    root to: "doctor/home#show"
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: "home#show"
  end
  resources :stripe_customers, only: [:new, :create]
  resources :chat_rooms, only: [:show] do
    get 'activate' => 'chat_rooms#activate'
    get 'deactivate' => 'chat_rooms#deactivate'
    resources :messages, only: [:create]
  end
  namespace :patient do
    resources :patients, only: [:new, :create]
    resources :doctors, only: [:show]
    resources :chat_rooms, only: [:create] do
      resources :chat_charges, only: [:new] do
        get 'stripe' => 'chat_charges#stripe', on: :collection
        post 'stripe' => 'chat_charges#stripe', on: :collection
        get 'paypal' => 'chat_charges#paypal', on: :collection
        get 'paypal_success' => 'chat_charges#paypal_success', on: :collection
      end
    end
  end

  namespace :doctor do
    resources :doctors, only: [:new, :create, :edit, :update]
  end
  get 'users/self/edit' => 'users#edit'

end

app/controllers/doctor/home_controller.rb
class Doctor::HomeController < Doctor::ApplicationController
  def show
    @chats = ChatRoom.includes(:messages).where(doctor: current_user).limit(5).map do |chat|
      chat if chat.messages.any? && chat.messages.first.author != current_user
    end.compact

    @number_of_patients = @chats.map(&:patient_id).uniq.count
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/patient/home_controller.rb
class Patient::HomeController < Patient::ApplicationController

  def show
    ids = Doctor.pluck(:id).map { |id| id if $redis_onlines.exists(id) }.compact
    @doctors = Doctor.where(id: ids)
  end
end

app/views/home/show.html.erb
<!-- <div class="container">
  <div class="home-page-main-nav">
    <%= link_to "I'm a patient", new_patient_patient_path, class: 'btn btn-black' %>
    <%= link_to "I'm a doctor", new_doctor_doctor_path, class: 'btn btn-black' %>
  </div>
</div> -->

<div id="screen1" class="screen">
  <div class="container">
    <main id="content">
      <div class="buttonpanel">
        <%= link_to "I'm a patient", new_patient_patient_path %>
        <%= link_to "I'm a doctor", new_doctor_doctor_path %>
        <!-- <a href="#">I'm a doctor</a> -->
      </div>
    </main>
    <footer id="footer">
      <div class="brand">We.</div>
      <nav id="nav"><a href="#">About</a><a href="#">How to use</a><a href="#">Contacts</a></nav>
    </footer>
  </div>
</div>